spring:
  application:
    name: employee
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:employee;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;DB_CLOSE_ON_EXIT=FALSE;INIT=create schema if not exists employee
server:
  port: 8080